# Site settings
title: gankai geekskai Blog
SEOTitle: "gankai 博客 | geekskai Blog"
header-img: "img/homePage.jpg"
email: "geeks.kai@gmail.com"
name: "ahrefs-site-verification"
content: "73e18207fdfc639fe75e40ce593597b93803f891984db47190a0b225bc676e06"
description: "Things that can make you miserable will surely make you strong, grow up, and must experience what others can't!"
keyword: "Vue, React, JavaScript, 博客, geekskai, ts, web, blog, js"
url: "https://geekskai.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/geekskai/blog.git" # you code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Always optimistic about the future!"
sidebar-avatar: /img/about-BY-gentle.png # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
weibo_username: 6131084360
zhihu_username: ren-qing-zi-ji-9
github_username: geekskai
# facebook_username:  baiying.qiu.7
jianshu_username: 4365773d2dd5
#twitter_username:   geekskai

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
# permalink: none
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: geekskai

# Gitalk
gitalk:
  enable: false #是否开启Gitalk评论
  clientID: d2223ef21ecae706fcb4 #生成的clientID
  clientSecret: 8fecef465f9f3dc81f11bd98ec59d4644eb9282a #生成的clientSecret
  repo: blog #仓库名称
  owner: geekskai #github用户名
  admin: geekskai
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 5b94756de87b260b647aed0a5ca70e7c

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 1 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends:
  [
    { title: "WY", href: "http://zhengwuyang.com" },
    { title: "简书·GK", href: "http://www.jianshu.com/u/4365773d2dd5" },
    { title: "Apple", href: "https://apple.com" },
    { title: "Apple Developer", href: "https://developer.apple.com/" },
  ]

theme: jekyll-theme-hacker
